<?php

/**
 * Implements hook_help().
 */
function vcard_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.vcard':
      return '<p>' . t('Provides a custom vCard field.', array()) . '</p>';
  }
}

/**
 * Implements hook_theme().
 */
function vcard_theme() {
  $themes = [];
  $themes['styleone'] = [
    'variables' => ['contact' => NULL],
  ];
  return $themes;
}
